button_actions.hpp
sf::Keyboard::Key Key
std::string name
Referenced by get_action_name_from_button_keys, item::get_name, item::get_in_game_name, sql::save_tiles.
float x
Referenced by game::game_loop, leveleditor::editor_loop, npc::move.
float y
Referenced by leveleditor::editor_loop.
const struct @0 actions[][]
Referenced by get_move_direction_from_button_keys, get_action_name_from_button_keys.
sf::Mouse::Button mouse_key
const struct @1 skills[][]
Referenced by get_skill_from_button_keys.
sf::Vector2f Vector2f_from_Vector2i(sf::Vector2i vector)
Convert a sf::vector2i to sf::Vector2f.
This method will convert a sf::Vector2i (a vector consisting 2 integer values), to a sf::Vector2f (a vector consisting 2 float values). Parameters: vector : sf::Vector2f -> Position to be converted.Return: Converted sf::Vector2i : sf::Vector2f -> Converted vector2i.Example: Vector2f_from_Vector2i({100 : int, 100 : int}) -> {100 : float, 100 : float}
Referenced by get_mouse_position.
std::string get_skill_from_button_keys()
Check if skill button is pressed.
This method will check if one of the buttons in the defined struct of skill_buttons is pressed. if that is the case, the method will return the name of the consisting skill. Return: skill_name : std::string -> name of the skill button that is pressed.Example: get_skill_from_button_keys() -> "shoot_arrow"
References skills.
Referenced by game::get_items_from_database.
sf::Vector2f get_move_direction_from_button_keys()
Get the move direction if move button is pressed.
This method will check if one of the buttons in the defined struct of move action buttons is pressed. if that is the case, the method will return the move direction of the consisting move. Return: direction : sf::Vector2f -> Direction in which the player should move. Example: get_move_direction_from_button_keys -> {-1, 0}
References actions.
Referenced by game::game_loop, game::get_items_from_database.
std::string get_action_name_from_button_keys()
Get the name of a move if move button is pressed.
This method will return the name from a move if one of the buttons, in the defined struct of move action buttons, is pressed. Return: direction : sf::Vector2f -> Direction in which the player should move. Example: get_action_name_from_button_keys() -> "walk_up"
References name, actions.
Referenced by game::get_items_from_database.
sf::Vector2f get_mouse_position(sf::RenderWindow &window)
Get the position of the mouse.
This method will return the position of the mouse on the window. Parameters: window : sf::RenderWindow& -> window to check the mouse on.Return: mouse position : sf::Vector2f -> Direction in which the player should move. Example: get_mouse_position( window) -> {100, 100}
References Vector2f_from_Vector2i.
Referenced by game::game_loop.
bool check_mouse()
Check if left mouse button is pressed.
This method will check if the left mouse button is pressed. If that is the case the function will return true. Return: button_pressed : bool -> If the mousebutton is pressed.Example: check_mouse() -> true