picture
sf::Texture picture::texture
sf::Sprite picture::sprite
std::string picture::picture_path
sf::Vector2f picture::tile_size
picture::picture(std::string picture_path, sf::Vector2f position, sf::Vector2f tile_size)
sf::FloatRect picture::getBounds()
void picture::rotate(float angle)
Referenced by main_menu::main_menu.
void picture::set_transpirantie(int value)
Referenced by main_menu::load_screen, main_menu::gid_gud_splash, main_menu::loading.
void picture::draw(sf::RenderWindow &window)
References figure::position.
Referenced by dialogbox::draw, leveleditor::editor_loop, main_menu::show_menu, main_menu::load_screen, main_menu::gid_gud_splash, main_menu::loading.