leveleditor
sf::Vector2f leveleditor::levelsize
sf::Vector2f leveleditor::rect_size
std::vector<figure*> leveleditor::rectangle_store
std::vector<picture*> leveleditor::background_store
std::vector<picture*> leveleditor::tile_store
std::vector<picture*> leveleditor::temporary_store
std::vector<dialogbox*> leveleditor::level_buttons
std::vector<std::string> leveleditor::level_ids
std::map<std::string, std::vector<std::string> > leveleditor::background_values_map
std::map<std::string, std::vector<std::string> > leveleditor::object_values_map
std::string leveleditor::active_level
sf::RenderWindow& leveleditor::window
sql& leveleditor::database
picture leveleditor::back_to_menu_button
picture leveleditor::save_level_button
picture leveleditor::new_game_button
picture leveleditor::load_game_button
bool leveleditor::pressed_esc
bool leveleditor::pressed_load_game
action leveleditor::actions[12][12]
sf::View leveleditor::view1
Referenced by leveleditor, editor_loop.
sf::View leveleditor::view2
Referenced by leveleditor, editor_loop.
sf::View leveleditor::view3
Referenced by leveleditor, editor_loop.
sf::View leveleditor::view4
Referenced by leveleditor, editor_loop.
bool leveleditor::button_pressed(dialogbox &object, sf::View &view)
Check if a button is pressed at the given view.
Parameters: object : dialogbox& -> A dialog object.view : view& -> A view.Return: bool : bool -> returns true if left mouse button is pressed on the given dialogbox.Example: Get_data(dialogbox, view1) return: {true}.
void leveleditor::get_items_from_database(std::map< std::string, std::vector< std::string >> &item_values_map)
Get data from the database by giving a map.
Parameters: map vector : std::map<std::string, std::vector<std::string>>& -> a map vector which contains a string with all the database values.Return: vector : std::vector<object> -> returns a vector with all the objects from the database.Example: get_items_from_database(object_map) -> item_map is now filled with objects.
void leveleditor::load_rectangles()
This function loads all background rectangles in the background vector.
This method will fill the rectangle_store with rectangles.
void leveleditor::load_tile_list()
This method loads all tiles which can be choosen at the right side of the level editor.
This method will fill the tile_store with objects.
void leveleditor::set_selected()
Set a object from the tile list as selected when there is clicked on it.
This method is used in the code to be able to switch between objects.
void leveleditor::remove_last_object()
Removes the last object from the temporary store.
This function removes the last object from the temporary store.
bool leveleditor::remove_object_under_mouse()
This function removes the object under the mouse by pressing c.
Return: bool : bool -> returns a bool.Example: remove_object_under_mouse() -> true
void leveleditor::create_object(sf::Vector2f position)
Creates an object which is selected at the given position.
Parameters: position : sf::Vector2f -> position for objectExample: Create_object({100,50}) Creates a selected object at position {100,50}.
sf::Vector2f leveleditor::convert_to_coords(sf::View &view)
Converts a mouse position to map coords on the given view.
Parameters: view : sf::View& -> view of the editorReturn: vector : sf::Vector2f -> A vector converted to mapcoords.Example: convert_to_coords(view1); -> (256,596)
sf::Vector2f leveleditor::get_position_from_rectangle_under_mouse()
Get the position of the rectangle from rectangle store under the mouse.
Return: position : sf::Vector2f -> A vector2f position.Example: get_position_from_rectangle_under_mouse() -> (234,262)
bool leveleditor::is_object_under_mouse(std::vector< picture *> &vector, sf::View &view)
Check if a picture object is under the mouse.
Parameters: vector : std::vector<picture*>& -> Give a picture vector with the function.view : sf::View -> Give a view with the function.Return: picture_under_mouse : bool -> Returns true if the mouse is on a object. Example: is_object_under_mouse(picture_vector, view1) -> true
bool leveleditor::is_object_under_mouse(std::vector< figure *> &vector, sf::View &view)
Check if a figure object is under the mouse.
Parameters: vector : std::vector<picture*>& -> Give a figure vector with the function. view : sf::View -> Give a view with the function. Return: figure_under_mouse : bool -> Returns true if the mouse is on a object. Example: is_object_under_mouse(figure_vector, view2) -> true
bool leveleditor::is_button_pressed(picture &object, sf::View &view)
Check if a button is pressed at the given view.
Parameters: object : 'picture& -> A picture object. view : view& -> A view. Return: button_pressed : bool -> returns true if left mouse button is pressed on the given picture. Example: Get_data(picture, view1) -> true
bool leveleditor::menu_options()
Looks if a menu button is pressed.
Return: back_to_menu_button_pressed : bool -> returns true if the back to menu button is pressed. sets other variables in the hpp on true or false if a button is pressed. Example: menu_options() -> true
leveleditor::leveleditor(sf::Vector2f levelsize, sf::Vector2f tilesize, sf::RenderWindow &window, sql &database)
Constructor.
This will create a leveleditor object. Parameters: levelsize : sf::Vector2f -> Give the levelsize with the function. tilesize : sf::Vector2f -> Give the tilesize with the function. window : sf::RenderWindow& -> Give a window with the function where the leveleditor needs to be drawn at. database : sql& -> Give the database to the function. Example: leveleditor({1080,1080}, {32,32}, window, database);
References view1, view2, view3, view4.
void leveleditor::editor_loop()
The main loop for the editor to stay working.
Example: editor_loop();
References view1, get_actions, draw_rectangle_store, draw_background_store, draw_temporary_store, view4, sql::get_available_levels, sql::get_level_ids, x, sql::get_level_background_value, sql::get_level_object_value, view2, draw_tile_store, view3, picture::draw, sql::set_new_map, sql::save_tiles, y, sql::get_object_sprite_ids, sql::get_object_sprite_value, rectangle::getBounds, figure::position.
void leveleditor::get_actions()
Loop through the actions in the action class.
Referenced by editor_loop.
void leveleditor::draw_rectangle_store()
Draw the rectangle store on the screen.
Example: draw_rectangle_store() rectangle_store is now drawn on the screen.
References rectangle::draw.
Referenced by editor_loop.
void leveleditor::draw_background_store()
Draw the background store.
Example: draw_background_store() background_store is now drawn on the screen.
Referenced by editor_loop.
void leveleditor::draw_tile_store()
Draw the tile store.
Example: draw_tile_store() Draw the objects from the tile_store.
Referenced by editor_loop.
void leveleditor::draw_temporary_store()
Draw the temporary store.
Example: draw_temporary_store() Draw the objects from the temporary_store.
Referenced by editor_loop.