main_menu
sf::RenderWindow& main_menu::window
picture main_menu::background
sf::View main_menu::view1
Referenced by main, main_menu, show_menu, load_screen.
sf::View main_menu::view2
Referenced by load_screen, gid_gud_splash, loading.
picture main_menu::level_editor_button
Referenced by main, main_menu, show_menu.
picture main_menu::play_game_button
Referenced by main, main_menu, show_menu.
picture main_menu::load_screen_pic
Referenced by main_menu, load_screen, loading.
picture main_menu::gid_gud
Referenced by main_menu, gid_gud_splash.
void main_menu::draw_main_menu()
main_menu::main_menu(sf::RenderWindow &window)
Constructor.
This method will crate an object of class main_menu. Parameters: window : sf::RenderWindow& -> refference to the SFML window. Example: main_menu m(window)
References level_editor_button, play_game_button, load_screen_pic, gid_gud, view1, picture::rotate.
void main_menu::show_menu()
Show menu.
This method shows the menu. Example: show_menu() -> You can now see the menu
References view1, button_pressed, level_editor_button, picture::draw, play_game_button.
Referenced by main, load_screen.
bool main_menu::button_pressed(picture &object, sf::View &view)
Ceck if a button is pressed.
This method return a boolean if a menu button is pressed with the mouse or not. Parameters: object : picture& -> refference to picture class object "object". view : sf::View& -> view where the mouse click is checked on. Return: button pressed : bool -> button pressed with mouseExample: button_pressed(play_game, menu_view) -> true
Referenced by main, show_menu.
void main_menu::load_screen()
Load the load screen.
This method will start a small loop, that smoothly change the main_menu to the load screen.
References show_menu, view1, picture::set_transpirantie, view2, load_screen_pic, picture::draw.
Referenced by main.
void main_menu::gid_gud_splash()
Creater screen.
This method will start the advertisement screen from the creators of the game.
References view2, gid_gud, picture::set_transpirantie, picture::draw.
Referenced by main.
void main_menu::loading()
start the load screen
This method will start draw the loadscreen pic. This is so that the player does not only see a black screen while waiting.
References view2, load_screen_pic, picture::set_transpirantie, picture::draw.
Referenced by main.