sql
sqlite3* sql::database
std::string sql::database_path
int sql::rc
int sql::connection
char* sql::_ERROR_MESSAGE
const char* sql::data
void sql::check_query_request()
Checks if query is executed correctly.
This method checks if the executed query is correctly procesed. If that is not the case this function will print an error on the command prompt. Example: check_query_request() no error, so do nothing
sql::sql()
sql::~sql()
std::vector< std::string > sql::get_data(char *table, char *columnname)
Get data from a column in a table in the database.
This method gets the data from a column in a table in the database. Parameters: table : char* -> Table name in the databasecolumn : char* -> Column name in the databaseReturn: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: Get_data("player", "level") return: {"1"}.
References execute_query_with_return.
Referenced by get_number_of_npcs, save_tiles, get_available_levels, get_level_ids, get_level_object_value, get_level_background_value, get_collision_objects.
std::vector< std::string > sql::get_data(char *table, char *columnname, char *condition1, char *condition2)
Get data from a column in a table in the database with condition.
This method gets the data from a table in the database, where the value of the given column meets the condition values.Parameters: table : char* -> Table name in the databasecolumn : char* -> Column name in the databasecondition1 : char* -> First condition of the Where statement in the SQL query.condition2 : char* -> Second condition of the Where statement in the SQL query.Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: Get_data("player", "name","id","1") return: {"arno"}.
References execute_query_with_return.
void sql::change_data(char *table, char *condition1, char *condition2, char *columnname, char *new_value)
Change values in the database.
This method overwrites data in the database, where the value of the given column meets the condition values.Parameters: table : char* -> Table name in the databasecondition1 : char* -> First condition of the Where statement in the SQL query.condition2 : char* -> Second condition of the Where statement in the SQL query.columnname : char* -> Column name in the databasenew_value : char* -> New value to be set in the specified column valueExample: change_data("player","id","1","name","pieter") The name of the player is now "pieter" instead of "arno"
References execute_query_without_return.
void sql::add_data(char *table, const char *values)
Add a new value to database.
This method adds a new value in the given table of the database. The parameter "value" is consists all the column values except the id, because the this value has auto increment.Parameters: table : char* -> Table name in the databasevalues : char* -> column values to add in the database.Example: add_data("sprites","'../../bin/objects/new_pic.png', new pic , 64 , 64") There is now a new record in the database with the given values.
References execute_query_without_return.
void sql::execute_query_without_return(const char *to_be_executed)
Execute a query.
This method executes a given query that has no return value. Parameters: to_be_executed : const char* -> Query to be executedExample: execute_query_without_return("INSERT INTO sprites VALUES(NULL, '../../bin/objects/new_pic.png', new pic , 64 , 64);") There is now a new record in the database with the given values.
References callback.
Referenced by add_data, add_item_to_inventory, change_data, set_new_map, save_tiles.
std::vector< std::string > sql::execute_query_with_return(const char *to_be_executed)
Execute a query.
This method executes a given query that has a return value. Parameters: to_be_executed : const char* -> Query to be executedReturn: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: execute_query_with_return("SELECT name FROM player WHERE id == 1;") Return: {"arno"}
References callback, get_result.
Referenced by get_data, get_inventory, get_name_from_id_inventory, get_sprite_inventory, get_in_game_name_from_id_inventory, get_player_value, get_player_sprite, get_npc_value, get_object_sprite_ids, get_object_sprite_value, save_tiles, get_level_object_value, get_level_background_value, get_collision_objects, get_music, get_quest_text, get_quest_parts.
std::vector< std::string > sql::get_name_from_id_inventory(std::string item_id)
Get the name from an item.
This function returns the name of an item by using its ID. Parameters: item_id : std::string -> The ID of the item. Return: name : std::vector<std::string> -> The name of the requested item.Example: get_name_from_id_inventory("1") -> tokato_gloves
References execute_query_with_return.
Referenced by item::get_name.
std::vector< std::string > sql::get_sprite_inventory(std::string item_id)
Get the sprite_path from an item.
This function returns the name of an item by using its ID. Parameters: sprite_path : std::string -> The ID of the item.Return: sprite_path : std::vector<std::string> -> The sprite_path of the requested item.Example: get_sprite_inventory("1") -> "../../bin/objects/banana.gif"
References execute_query_with_return.
Referenced by item::get_sprite.
std::vector< std::string > sql::get_in_game_name_from_id_inventory(std::string item_id)
Get the name from an item.
This function returns the name of an item by using its ID. Parameters: item_id : std::string -> The ID of the item.Return: name : std::vector<std::string> -> The in game name of the requested item.Example: get_name_from_id_inventory("1") -> Tokato Gloves
References execute_query_with_return.
Referenced by item::get_in_game_name.
std::vector< std::string > sql::get_inventory()
Get the inventory.
This function retrieves the inventory and its values and puts it into a vector. Return: inventory_vector : std::vector<std::string> -> This vector contains the items in the inventoryExample: get_inventory() -> {"1", "2", "2", "3"}
References execute_query_with_return.
Referenced by inventory::get_inventory.
std::vector< std::string > sql::get_player_value(int save, std::string variable_name)
Get value of a column from the player.
This method returns a column value of the player. The save is equal the the player id in the database, this is because the player can have multiple saved games. Parameters: save : int -> Save of the player and player id in the database.variable_name : std::string -> Columnname from what the value is requested.Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_player_value(1,"name") -> {"arno"}
References execute_query_with_return.
Referenced by npc::npc, player::player.
std::vector< std::string > sql::get_player_sprite(int save)
Get sprite sheet of the player.
This method returns the sprite sheet of the player. The save is equal the the player id in the database, this is because the player can have multiple saved games. Parameters: save : int -> Save of the player and player id in the database.Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_player_sprite(1) -> {"../../bin/sprite_sheets/player_sprite.png"}
References execute_query_with_return.
std::vector< std::string > sql::get_player_value(std::string npc_id)
Get value of the player.
This method returns the value of a player. The player value is calculated on the player_id. Parameters: npc_id : std::string -> Save of the player and player id in the database.Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_player_sprite(1) -> {"../../bin/sprite_sheets/player_sprite.png"}
References execute_query_with_return.
void sql::add_item_to_inventory(std::string item_id)
Add an item to the players inventory.
This function will give the player an item that will be stored in the inventory table in the database. Parameters: item_name : std::string -> The name of the item that has to be givenExample: add_item_to_inventory("1"); -> Adds a banana to the users inventory
References execute_query_without_return.
Referenced by game::game_loop.
std::vector< std::string > sql::get_npc_value(std::string npc_id)
Get all values from columns in NPC.
This method returns all column values of a NPC. The order of the returning values in the vector is: index | name of value ---------------------- 0 | name 1 | level 2 | class_id 3 | sprite_id 4 | position_x 5 | position_y 6 | quest_id Parameters: npc_id : std::string -> ID of the NPC from whom the values are asked.Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_npc_value("1") -> {"arno"}
References execute_query_with_return.
Referenced by npc::npc.
std::vector< std::string > sql::get_number_of_npcs()
Get all id's of the NPC's.
This method returns all id values of the NPC table. The lengths of the vector is equal to how many NPC's there are in the table. Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_number_of_npcs() -> {"1","2","5"}
References get_data.
Referenced by game::get_items_from_database.
std::vector< std::string > sql::get_object_sprite_ids()
Get id's from objects and tiles sprites.
This method returns all sprite id values of tiles and objects. Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_object_sprite_ids() -> {"1","2","5"}
References execute_query_with_return.
Referenced by leveleditor::editor_loop.
std::vector< std::string > sql::get_object_sprite_value(std::string object_id)
Get all values from columns in sprites.
This method returns all column values of a a sprite. The order of the returning values in the vector is: index | name of value ---------------------- 0 | path 1 | name 2 | sprite_size_x 3 | sprite_size_y Parameters: object_id : std::string -> ID of the object/tile from what the values are asked.Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_object_sprite_value("1") -> {"../../bin/objects/road1.png", "road1","32","32"}
References execute_query_with_return.
Referenced by leveleditor::editor_loop.
void sql::set_new_map(std::string map_name, int background_music)
Create new map.
This method creates a new record in the maps table. This record consists the map_id, map name and the corresponding background music. Parameters: map_name : std::string -> name of the level that has to be created.background_music : int -> id of the background music of the level.Example: set_new_map("level1",1) There is now a new maps record in the database, that has the name level1 with brackground_id 1.
References execute_query_without_return.
Referenced by leveleditor::editor_loop.
void sql::save_tiles(std::string tile_path, int pos_x, int pos_y, std::string map_name)
Saves the tiles in the database.
This method saves a tile in the database. The tile values will be filterd if it is an object or an background tile. It is very importend that if you want to save the level, that the map_name is spelled correctly. If the map_name is not correctly spelled or if it doesn't exist, the level cannot be saved. The same counts for the tile path. Parameters: tile_path : std::string -> path to the consisting image of the object/tile.pos_x : int -> x position where the object/tile should be placed in the map.pos_y : int -> y position where the object/tile should be placed in the map.map_name : std::string -> name of the map where the object/tile will be placed in.Example: save_tiles("../../bin/objects/example.png",10,10,"level1") This object is now saved in the objects table, with a refference that is has to be placed in level1.
References get_data, name, execute_query_with_return, execute_query_without_return.
Referenced by leveleditor::editor_loop.
std::vector< std::string > sql::get_available_levels()
Get the names of all levels in the database.
This method returns all names of the levels that are in the database. This can be usefull so you can know if a level already exists. Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_available_levels() -> {"level1","level2","level5"}
References get_data.
Referenced by leveleditor::editor_loop.
std::vector< std::string > sql::get_level_ids()
Get the ID's of all levels in the database.
This method returns all ID's of the levels that are in the database. Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_level_ids() -> {"1","2","5"}
References get_data.
Referenced by game::game, leveleditor::editor_loop, main.
std::map< std::string, std::vector< std::string > > sql::get_level_object_value(std::string level_id)
Get all object values of a level.
This method returns the values of all objects that are assigned to the given level ID. Parameters: level_id : std::string -> id of the level from what the objects have to be loaded.Return: list_of_data : std::map<std::string, std::vector<std::string>> -> map that contains the asked data in the form of strings with name as key. Example: get_level_object_value("level1") -> {"road1":{"../../bin/objects/example.png","120","150","1"}}
References get_data, execute_query_with_return.
Referenced by game::game, leveleditor::editor_loop.
sf::IntRect sql::get_collision_objects(std::vector< std::string > objects)
Get the not walkable objects.
This method returns the hitbox of an object that is not walkable. The hitbox can be used to calculate the collision detection on. Parameters: objects : std::vector<std::string> -> values of one opbject.Return: collision_rects : sf::IntRect -> Hitbox of the not walkable object. Example: get_collision_objects({...}) -> (100,100,50,50)
References get_data, execute_query_with_return.
Referenced by game::game.
std::map< std::string, std::vector< std::string > > sql::get_level_background_value(std::string level_id)
Get all background values of a level.
This method returns the values of all background tiles that are assigned to the given level ID. Parameters: level_id : std::string -> id of the level from what the background tiles have to be loaded.Return: list_of_data : std::map< std::string, std::vector<std::string> > -> Map that contains the asked data in the form of strings with name as key. Example: get_level_object_value("level1") {"road1":{"../../bin/tiles/example.png","120","150","1"}}
References get_data, execute_query_with_return.
Referenced by game::game, leveleditor::editor_loop.
std::vector< std::string > sql::get_music(std::string map_id)
Get music of consisting map.
This method returns the path of a music file what is the background music of a level. The values are searched by the ID of the map. Parameters: map_id : std::string -> ID of the level where the music file is requested.Return: list_of_data : std::vector<std::string> -> list that contains the asked data in the form of strings. Example: get_music("17") -> ../../bin/music/x_gon_give_it_to_ya.wav
References execute_query_with_return.
Referenced by music::play_music_from_map.
std::vector< std::string > sql::get_quest_text(std::string quest_id, std::string part)
Get quest part text.
This method returns the text of a quest part. The values are searched by the ID of the of the quest and the given part number. Parameters: quest_id : std::string -> ID of the quest from what the text is requested. part : std::string -> number of the part in the quest where the text is requested from. Return: list_of_data : std::vector<std::string> -> list that contains the asked data in the form of strings. Example: get_quest_text("17") -> {"Hello.","welcome"}
References execute_query_with_return.
Referenced by game::game, game::game_loop.
std::vector< std::string > sql::get_quest_parts(std::string quest_id)
Get all part numbers from quest.
This method returns the numbers of quest parts of a quest. The values are searched by the ID of the quest. Parameters: quest_id : std::string -> ID of the quest from what the text is requested. Return: list_of_data : std::vector<std::string> -> list that contains the asked data in the form of strings. Example: get_quest_parts("1") -> {"1","3","4","5","6"}
References execute_query_with_return.
Referenced by game::game, game::game_loop.
std::vector< std::string > sql::get_result()
Get saved result.
This method returns the result that is stored in the global result value. the result value is a global and static because it is set by the callback function. Return: list_of_data : std::vector<std::string> -> List that contains the asked data in the form of strings.Example: get_result() Return: {"arno"}
Referenced by execute_query_with_return.
static void sql::set_result(char *x)
Save result to static value.
This method adds a new value, what is a result of an query, to the static string vector result. It does not overwrite it because there could be a result of multiple strings. This function is only called by the static callback function. Parameters: x : char* -> Query result to add.Example: set_result("arno") Last value in result is now "arno".
Referenced by callback.
int sql::callback(void *NotUsed, int argc, char **argv, char **azColName)
Get value from database.
This method is used to get the value from the database. What the function does is explained in the sqlite3.hpp file. In this class we use it to store the found data in a global static value.
References set_result.
Referenced by execute_query_without_return, execute_query_with_return.