player
npc player::player_npc
std::string player::player_id
sf::Vector2f player::spawn
sf::Vector2f player::position
sf::Vector2f player::last_move
sql player::database
player::player(sf::RenderWindow &window, sql &database, std::string save)
Constructor.
This method will create an object of class npc. Parameters: window : sf::RenderWindow -> window where content will be drawn on.database : sql -> referrence to the database class. save : sf::string -> id of the current game save.Example: player a(window, database, "1")
References npc::draw, sql::get_player_value.
void player::move(sf::Vector2f delta)
void move() : Move the player
This method moves the position the player. Parameters: delta : sf::Vector2f -> new position of the player.Example: move({2,0}) player has moved 2 pixels to the right
References npc::move.
Referenced by game::get_items_from_database.
void player::set_action(std::string s)
void set_action(std::string s) : Set action of the player
This method sets the current action of the player. The standard value is walk down. Parameters: s : std::string -> name of the action that has to be set on active.Example: set_action("walk_up") -> Player is now set for walking up.
References npc::set_action.
Referenced by game::get_items_from_database.
void player::draw()
void draw() : Print player
This method draws the player on the screen. Example: draw() -> Draw the player on the screen
References npc::draw.
Referenced by game::get_items_from_database.
void player::respawn()
void respawn() : Respawn player
This method moves the player back to a specific location Example: respawn() -> Player will be moved back to (200,200)
References npc::set_position.
Referenced by game::game_loop.
int player::get_interaction(npc &other_npc)
int npc::get_interaction(npc & other_npc) : Get interaction between the player and a NPC
Call the 'get_interaction' function to check for a collision between the player and a NPCParameters: other_npc : NPC & -> The NPC that will be checked with for a collisionReturn: 0 / 1 : integer -> Return a 1 if there's a collision detected, return a 0 if no collision is detectedExample: get_interaction(*other_npc) -> return: {"1"}.
References npc::get_interaction.
Referenced by game::game_loop, game::get_items_from_database.
int player::get_collision(sf::IntRect colliding_object)
int get_collision(sf::IntRect colliding_object) : Get interaction between a NPC and a sf::IntRect object
Call the 'get_collision' function to check for a collision with a sf::IntRect objectParameters: colliding_object : sf::IntRect -> The sf::IntRect that will be check for a collisionReturn: 0 / 1 : integer -> Return a 1 if there's a collision detected, return a 0 if no collision is detectedExample: get_collision(recangle) -> return: {"1"}.
References npc::get_collision.
Referenced by game::get_items_from_database.
void player::set_last_position()
void set_last_position() : Set the position back to its last position
When this function is called, the current location will be set to last locationExample: set_last_position() -> The position is now set to the last position
References npc::set_position.
Referenced by game::get_items_from_database.
sf::Vector2f player::get_position()
sf::Vector2f get_position() : Get position of player
When this function is called, it will return the position of the playerReturn: position : sf::Vector2f -> The position of the playerExample: get_position() -> return sf::Vector(200,200)
References npc::get_position.
std::vector< sf::Sprite > player::get_action(std::string action_to_get)
void show_action(std::string action_to_perform) : Player acion
This function displays the right action of the player, so the right spritepart that displays the current action of the player, like walking upParameters: action_to_perform : std::string -> The action that has to be shownExample: show_action("walk_up") -> Now the player seems to be walking up
References npc::get_action.
Referenced by game::get_items_from_database.
std::string player::get_current_action()
Get current action the player.
This function returns the name of the current action of the player. This is the action that the player is currently performing in the game. Return: current_action : std::string -> Name of the current action from the player.Example: get_current_action() -> "walk_up"
References npc::get_current_action.
Referenced by game::get_items_from_database.
void player::show_ability(std::string action_to_show)
Perform an action.
This function shows one step of the asked ability. This function has to be called in a loop that stops at the max size of the ability list. Parameters: action_to_show : std::string -> Name of action.Example: show_ability("shoot_arrow_up") -> the player will shoot an arrow northwards.
References npc::show_ability.
Referenced by game::get_items_from_database.
void player::set_position(sf::Vector2f new_position)
Get position of the player.
When this function is called, it will return the position of the player. Return: position : sf::Vector2f -> The position of the playerExample: get_position() -> return sf::Vector(200,200)
References npc::set_position.
player::~player()
Decontructor.
Will be called when the object is deleted.