npc
std::vector<ability*> npc::npc_actions
std::vector<std::string> npc::npc_values
std::string npc::id
sf::Vector2f npc::position
sql& npc::database
int npc::sprite_size
sf::Texture npc::texture
sf::RenderWindow& npc::window
std::string npc::current_action
bool npc::is_player
void npc::load_all_actions()
Load all abilities.
This method will load all abilities of an NPC sprite sheet.
void npc::load_action(std::string action_name, int steps_of_action, int level)
Load a npc ability.
This method will load one ability of an NPC sprite sheet. This ability has a certain ammount of steps and stands on a certain level in the sprite sheet. Parameters: action_name : std::string -> name of the ability to loadsteps_of_action : int -> ammount of steps of the ability.
npc::npc(sf::RenderWindow &window, sql &database, std::string npc_id, bool is_player=false)
Constructor.
This method will crate an object of class npc. Parameters: window : sf::RenderWindow -> window where content will be drawn on.database : sql -> referrence to the database class. npc_id : sf::string -> id of the npc that has to be drawn.is_player : bool -> boolean to select if this npc is the player or not.Example: ability a(window, database, "1")
References sql::get_player_value, sql::get_npc_value.
void npc::move(sf::Vector2f delta)
Move the npc.
This method moves the position an npc. Parameters: delta : sf::Vector2f -> new position of the npc.Example: move({2,0}) npc has moved 2 pixels to the right
References x.
Referenced by player::move.
void npc::set_action(std::string s="0")
set action of npc
This method sets the current action of the npc. The standard value is walk down. Parameters: s : std::string -> name of the action that has to be set on active.Example: set_action("walk_up") npc is now set for walking up.
Referenced by player::set_action.
std::string npc::get_name()
Get the name of npc.
This method returns the name of an npc. Return: name : std::String -> name of the abilityExample: get_name() "monk"
const void npc::draw()
void draw() : Print NPC
This method draws the NPC on the screen. Example: draw() -> Draw the NPC on the screen
Referenced by player::player, player::draw.
sf::IntRect npc::get_bounds()
Get a bounds from a NPC.
This function returns a sf::IntRect object which is created from the position and size of the NPC object. Return: intrect_object : sf::IntRect -> a sf::IntRect object using the position and size of the NPC objectExample: get_bounds() return: sf::IntRect(100, 100, 30, 30) .
Referenced by get_collision, get_interaction.
int npc::get_interaction(npc &other_npc)
Get interaction two NPC's.
Call the 'get_interaction' function to check for a collision with another NPC.Parameters: other_npc : NPC & -> The NPC that will be check for a collision.Return: 0 / 1 : integer -> Return a 1 if there's a collision detected, return a 0 if no collision is detected.Example: get_interaction(*other_npc) -> return: {"1"}.
References get_bounds.
Referenced by player::get_interaction.
int npc::get_collision(sf::IntRect colliding_object)
Get interaction NPC and object.
Call the 'get_collision' function to check for a collision with a sf::IntRect object. Parameters: colliding_object : sf::IntRect -> The sf::IntRect that will be check for a collision. Return: 0 / 1 : integer -> Return a 1 if there's a collision detected, return a 0 if no collision is detected. Example: npc.get_collision(recangle) return: {"1"}.
References get_bounds.
Referenced by player::get_collision.
void npc::set_position(sf::Vector2f given_position)
Get position of NPC.
When this function is called, it will return the position of the NPC. Return: position : sf::Vector2f -> The position of the NPCExample: get_position() -> return sf::Vector(200,200)
Referenced by player::set_last_position, player::respawn, player::set_position.
sf::Vector2f npc::get_position()
Get position of NPC.
When this function is called, it will return the position of the NPC.Return: position : sf::Vector2f -> The position of the NPCExample: get_position() -> return sf::Vector(200,200)
References get_action, get_current_action, show_ability, ~npc.
Referenced by player::get_position.
std::vector< sf::Sprite > npc::get_action(std::string action_to_get)
Get NPC action.
This function return a list of sprites that is asked from the NPC. Parameters: action_to_perform : std::string -> The action that has to be shown.Return: temp : std::vector<sf::Sprite> -> list of sprites containing the sprites of an ability.Example: get_action("walk_up") -> {sprite1,sprite2,....}
Referenced by get_position, player::get_action.
std::string npc::get_current_action()
Get current action of NPC.
This function returns the name of the current action of a NPC. This is the action that the NPC is currently performing in the game. Return: current_action : std::string -> Name of the current action from NPC.Example: get_current_action() -> "walk_up"
Referenced by get_position, player::get_current_action.
void npc::show_ability(std::string action_to_show)
Perform an action.
This function shows one step of the asked ability. This function has to be called in a loop that stops at the max size of the ability list. Parameters: action_to_show : std::string -> Name of action.Example: show_ability("shoot_arrow_up") -> NPC will shoot an arrow northwards.
Referenced by get_position, player::show_ability.
npc::~npc()
Decontructor.
Will be called when the object is deleted.
Referenced by get_position.