.TH "circle" 3 "Fri Feb 3 2017" "Version Version: alpha v1.5" "Git Gud: The adventures of the hungover" \" -*- nroff -*-
.ad l
.nh
.SH NAME
circle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.hpp>\fP
.PP
Inherits \fBfigure\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcircle\fP (sf::Vector2f \fBposition\fP, float size, sf::Color color)"
.br
.ti -1c
.RI "sf::FloatRect \fBgetBounds\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (sf::RenderWindow &window)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBsize_in\fP"
.br
.ti -1c
.RI "sf::Color \fBset_color\fP"
.br
.ti -1c
.RI "sf::CircleShape \fBcirc\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 36 of file objects\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "circle::circle (sf::Vector2f position, float size, sf::Color color)"

.PP
Definition at line 31 of file objects\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void circle::draw (sf::RenderWindow & window)\fC [virtual]\fP"

.PP
Implements \fBfigure\fP\&.
.PP
Definition at line 69 of file objects\&.cpp\&.
.SS "sf::FloatRect circle::getBounds ()\fC [virtual]\fP"

.PP
Implements \fBfigure\fP\&.
.PP
Definition at line 57 of file objects\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "sf::CircleShape circle::circ\fC [private]\fP"

.PP
Definition at line 40 of file objects\&.hpp\&.
.SS "sf::Color circle::set_color\fC [private]\fP"

.PP
Definition at line 39 of file objects\&.hpp\&.
.SS "float circle::size_in\fC [private]\fP"

.PP
Definition at line 38 of file objects\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Git Gud: The adventures of the hungover from the source code\&.
