.TH "invalid_position" 3 "Fri Feb 3 2017" "Version Version: alpha v1.5" "Git Gud: The adventures of the hungover" \" -*- nroff -*-
.ad l
.nh
.SH NAME
invalid_position
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception_list\&.hpp>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinvalid_position\fP (char c)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const override"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file exception_list\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "invalid_position::invalid_position (char c)\fC [inline]\fP"

.PP
Definition at line 27 of file exception_list\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const char* invalid_position::what () const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 30 of file exception_list\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string invalid_position::s\fC [private]\fP"

.PP
Definition at line 25 of file exception_list\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Git Gud: The adventures of the hungover from the source code\&.
