.TH "music" 3 "Fri Feb 3 2017" "Version Version: alpha v1.5" "Git Gud: The adventures of the hungover" \" -*- nroff -*-
.ad l
.nh
.SH NAME
music
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <music\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmusic\fP (\fBsql\fP &\fBdatabase\fP, sf::SoundBuffer \fBbuffer\fP, sf::Sound \fBsound\fP)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "void \fBset_volume\fP (int i)"
.br
.RI "Set music volume\&. "
.ti -1c
.RI "void \fBplay_music_from_map\fP (std::string map_id)"
.br
.RI "Play map music\&. "
.ti -1c
.RI "void \fBstop_music\fP ()"
.br
.RI "Stop the music\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "sf::SoundBuffer \fBbuffer\fP"
.br
.ti -1c
.RI "sf::Sound \fBsound\fP"
.br
.ti -1c
.RI "sf::Music \fBintro\fP"
.br
.ti -1c
.RI "\fBsql\fP \fBdatabase\fP"
.br
.ti -1c
.RI "std::string \fBpath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file music\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "music::music (\fBsql\fP & database, sf::SoundBuffer buffer, sf::Sound sound)"

.PP
Constructor\&. This method will crate an object of class music\&.
.br
.PP
.SS "Parameters: "
.PP
database : sql& 
.br
-> refference to the sqlite database\&.
.br
 buffer : sf::SoundBuffer 
.br
-> a sf::SoundBuffer\&.
.br
 sound : sf::Sound 
.br
-> a sf::sound\&.
.br
.PP
.SS "Example: "
.PP
music m(database, buffer, sound)
.br

.PP
Definition at line 3 of file music\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void music::play_music_from_map (std::string map_id)"

.PP
Play map music\&. Play the music that belongs to a specific map 
.br
 
.SS "Parameters: "
.PP
map_id : std::string 
.br
-> The map of which the music has to be played 
.br
 
.SS "Example: "
.PP
play_music_from_map('1') 
.br
-> Play the music from map 1 
.br

.PP
Definition at line 13 of file music\&.cpp\&.
.SS "void music::set_volume (int i)"

.PP
Set music volume\&. This function changes the volume of the played music 
.br
 
.SS "Parameters: "
.PP
i : int 
.br
-> The volume strength 
.br
 
.SS "Example: "
.PP
set_volume(100) 
.br
-> Volume has been set to 100 
.br

.PP
Definition at line 9 of file music\&.cpp\&.
.SS "void music::stop_music ()"

.PP
Stop the music\&. This function stops the music 
.br
 
.SS "Example: "
.PP
\fBstop_music()\fP 
.br
-> Music has been stopped 
.br

.PP
Definition at line 35 of file music\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "sf::SoundBuffer music::buffer\fC [private]\fP"

.PP
Definition at line 8 of file music\&.hpp\&.
.SS "\fBsql\fP music::database\fC [private]\fP"

.PP
Definition at line 11 of file music\&.hpp\&.
.SS "sf::Music music::intro\fC [private]\fP"

.PP
Definition at line 10 of file music\&.hpp\&.
.SS "std::string music::path\fC [private]\fP"

.PP
Definition at line 12 of file music\&.hpp\&.
.SS "sf::Sound music::sound\fC [private]\fP"

.PP
Definition at line 9 of file music\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Git Gud: The adventures of the hungover from the source code\&.
