.TH "rectangle" 3 "Fri Feb 3 2017" "Version Version: alpha v1.5" "Git Gud: The adventures of the hungover" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rectangle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <objects\&.hpp>\fP
.PP
Inherits \fBfigure\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrectangle\fP (sf::Vector2f \fBposition\fP, sf::Vector2f size, float outline_thickness, sf::Color color, sf::Color outline_color)"
.br
.ti -1c
.RI "sf::FloatRect \fBgetBounds\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (sf::RenderWindow &window)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "sf::Vector2f \fBsize_in\fP"
.br
.ti -1c
.RI "sf::Color \fBset_color\fP"
.br
.ti -1c
.RI "sf::RectangleShape \fBrect\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 48 of file objects\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rectangle::rectangle (sf::Vector2f position, sf::Vector2f size, float outline_thickness, sf::Color color, sf::Color outline_color)"

.PP
Definition at line 41 of file objects\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void rectangle::draw (sf::RenderWindow & window)\fC [virtual]\fP"

.PP
Implements \fBfigure\fP\&.
.PP
Definition at line 74 of file objects\&.cpp\&.
.SS "sf::FloatRect rectangle::getBounds ()\fC [virtual]\fP"

.PP
Implements \fBfigure\fP\&.
.PP
Definition at line 61 of file objects\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "sf::RectangleShape rectangle::rect\fC [private]\fP"

.PP
Definition at line 52 of file objects\&.hpp\&.
.SS "sf::Color rectangle::set_color\fC [private]\fP"

.PP
Definition at line 51 of file objects\&.hpp\&.
.SS "sf::Vector2f rectangle::size_in\fC [private]\fP"

.PP
Definition at line 50 of file objects\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Git Gud: The adventures of the hungover from the source code\&.
