-- MySQL Script generated by MySQL Workbench
-- 01/19/17 13:14:47
-- Model: database_design    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`NPC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NPC` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NPC` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  `class` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NPC_properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NPC_properties` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NPC_properties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `health` INT NOT NULL DEFAULT 1,
  `armor` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`quest` ;

CREATE TABLE IF NOT EXISTS `mydb`.`quest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `triggered` INT NOT NULL DEFAULT 0,
  `active` INT NOT NULL DEFAULT 0,
  `parts` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`music`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`music` ;

CREATE TABLE IF NOT EXISTS `mydb`.`music` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`maps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`maps` (
  `id` INT NOT NULL,
  `naam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stories` (
  `quest_id` INT NOT NULL,
  `part` INT NOT NULL,
  `spreaker` INT NOT NULL,
  `text` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`quest_id`, `part`),
  CONSTRAINT `id`
    FOREIGN KEY (`quest_id`)
    REFERENCES `mydb`.`quest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
