.TH "end_of_file" 3 "Fri Feb 3 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
end_of_file
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception_list\&.hpp>\fP
.PP
Inherits exception\&.
.SH "Detailed Description"
.PP 
Definition at line 5 of file exception_list\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
