.TH "game" 3 "Fri Feb 3 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgame\fP (sf::RenderWindow &window, \fBsql\fP &database, sf::Vector2f levelsize)"
.br
.RI "The constructor\&. "
.ti -1c
.RI "void \fBgame_loop\fP ()"
.br
.RI "Loop that handles the game\&. "
.ti -1c
.RI "void \fBget_items_from_database\fP (std::map< std::string, std::vector< std::string >> &item_values_map)"
.br
.RI "Get the items from the database\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file game\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "game::game (sf::RenderWindow & window, \fBsql\fP & database, sf::Vector2f levelsize)"

.PP
The constructor\&. The constructor of the 'game' class, this creates a game object\&.
.br
.PP
.SS "Parameters: "
.PP
levelsize : sf::Vector2f 
.br
-> The size of the level
.PP
database : sql & 
.br
-> A 'SQ' object, this will be used to get information from the database
.PP
window :sf::RenderWindow 
.br
-> The window on which the game has to be drawn
.PP
.SS "Example: "
.PP
\fBgame(window, database, levelsize)\fP 
.br
.IP "\(bu" 2
> This will create a 'game' object 
.PP

.PP
Definition at line 3 of file game\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void game::game_loop ()"

.PP
Loop that handles the game\&. This funtion will execute everything that will be needed to run the game, 
.br
like drawing the window, loading the NPC's and working with them
.PP
.SS "Example: "
.PP
\fBgame_loop()\fP 
.br
.IP "\(bu" 2
> This will start the game 
.PP

.PP
Definition at line 52 of file game\&.cpp\&.
.SS "void game::get_items_from_database (std::map< std::string, std::vector< std::string >> & item_values_map)"

.PP
Get the items from the database\&. This function gets all the items from the database and places it in a std::map\&.
.br
.PP
.SS "Parameters: "
.PP
item_values_map : std::map<std::string, std::vector<std::string>> & 
.br
-> The map that contains all the items and its location
.PP
.SS "Example: "
.PP
get_items_from_database(background_values_map) 
.br
.IP "\(bu" 2
> The std::map will be filled with the items 
.PP

.PP
Definition at line 236 of file game\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
