.TH "inventory" 3 "Fri Feb 3 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inventory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inventory\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinventory\fP (sf::RenderWindow &window, \fBsql\fP &database)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "void \fBget_inventory\fP ()"
.br
.RI "void \fBget_inventory()\fP : Get the inventory "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file inventory\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "inventory::inventory (sf::RenderWindow & window, \fBsql\fP & database)"

.PP
Constructor\&. This method will crate an object of class inventory\&.
.br
.PP
.SS "Parameters: "
.PP
window : sf::Renderwindow& 
.br
-> window the inventory hs to be drawn one\&.
.PP
database : sql& 
.br
-> refference to the sqlite database\&.
.br
.PP
.SS "Example: "
.PP
inventory inv(window, database)
.br

.PP
Definition at line 3 of file inventory\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void inventory::get_inventory ()"

.PP
void \fBget_inventory()\fP : Get the inventory This function returns the items in the inventory
.PP
.SS "Example: "
.PP
get_inventory(1) 
.br
-> Shows the items in the inventory 
.PP
Definition at line 8 of file inventory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
