.TH "D:/Documents-(D)/HBO-ICT/jaar2/Blok B/git/game_development/Software/Maingame/src/main.cpp" 3 "Fri Feb 3 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Documents-(D)/HBO-ICT/jaar2/Blok B/git/game_development/Software/Maingame/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'sqlite3\&.h'\fP
.br
\fC#include 'sql\&.hpp'\fP
.br
\fC#include <SFML\\Graphics\&.hpp>\fP
.br
\fC#include 'button_actions\&.hpp'\fP
.br
\fC#include 'player\&.hpp'\fP
.br
\fC#include 'music\&.hpp'\fP
.br
\fC#include 'main_menu\&.hpp'\fP
.br
\fC#include 'game\&.hpp'\fP
.br
\fC#include 'leveleditor\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBintro\fP (sf::Music &m, std::string path)"
.br
.ti -1c
.RI "void \fBintro_stop\fP (sf::Music &m)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void intro (sf::Music & m, std::string path)"

.PP
Definition at line 13 of file main\&.cpp\&.
.SS "void intro_stop (sf::Music & m)"

.PP
Definition at line 20 of file main\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 24 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
