.TH "D:/Documents-(D)/HBO-ICT/jaar2/Blok B/git/game_development/Software/Maingame/src/objects.hpp" 3 "Fri Feb 3 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Documents-(D)/HBO-ICT/jaar2/Blok B/git/game_development/Software/Maingame/src/objects.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfigure\fP"
.br
.ti -1c
.RI "class \fBpicture\fP"
.br
.ti -1c
.RI "class \fBcircle\fP"
.br
.ti -1c
.RI "class \fBrectangle\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
