.TH "unknown_shape" 3 "Fri Feb 3 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unknown_shape
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exception_list\&.hpp>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunknown_shape\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file exception_list\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "unknown_shape::unknown_shape (const std::string & name)\fC [inline]\fP"

.PP
Definition at line 40 of file exception_list\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const char* unknown_shape::what () const\fC [inline]\fP, \fC [override]\fP"

.PP
Definition at line 44 of file exception_list\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
